spring.application.name=springboot
server.port=8071

file.upload-path=E:/Javatest/

aliyun.oss.endpoint=https://oss-cn-shenzhen.aliyuncs.com
aliyun.oss.access-key-id=${OSS_ACCESS_KEY_ID}
aliyun.oss.access-key-secret=${OSS_ACCESS_KEY_SECRET}
aliyun.oss.bucket-name=liuzimu1
aliyun.oss.region=cn-shenzhen